version: '2.28.1'
volumes:
  mysql:
    driver: local
  rvf-store:
    driver: local

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=snomed
      - MYSQL_USER=rvf_user
      - MYSQL_PASSWORD=snomedrvf
      - MYSQL_DATABASE=rvf_master
    networks:
      rvf_net:
        aliases:
          - sql
    volumes:
      - mysql:/var/lib/mysql
    command:
      mysqld --sql_mode="NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES" --lower_case_table_names=1
  rvf:
    image: snomedinternational/release-validation-framework:latest
    container_name: rvf
    depends_on:
      - db
    entrypoint: java -Xms512m -Xmx4g -Daws.region=us-east-1 -cp @/app/jib-classpath-file org.ihtsdo.rvf.App --server.port=8081 --server.servlet.context-path=/api
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/?useSSL=false&allowLoadLocalInfile=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=snomed
      - rvf.assertion.resource.local.path=snomed-release-validation-assertions
      - rvf.drools.rule.directory=snomed-drools-rules
      - spring.security.user.name=rvf_user
      - spring.security.user.password=snomed
    networks:
      - rvf_net
    volumes:
      - rvf-store:/app/store
      - type: bind
        source: ./store/releases
        target: /app/store/releases
    restart: always

networks:
  rvf_net:
