package org.ihtsdo.rvf.validation;

public enum ColumnType {

	UUID, TIME, BOOLEAN, INTEGER, NON_ZERO_INTEGER, REGEX, REL_UUID, REL_SCTID, REL_TIME, STRING, SCTID_OR_UUID, REL_SCTID_OR_UUID, SCTID

}
