#!/bin/sh -e

#For debugging uncomment these two lines
set -x
echo $*

APP_NAME=[[packageName]]

supervisorctl update $APP_NAME || true
supervisorctl start $APP_NAME || true

# Database command safe to run both on install and upgrade
echo "Creating RVF mysql database and user"
mysql -u root -e "CREATE DATABASE IF NOT EXISTS rvf_master; GRANT ALL PRIVILEGES  ON rvf_master.* TO 'rvf_user'@'localhost' ;"

